
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[346] =
    {   0,
        0,    0,   40,   40,    0,    0,   69,   67,   66,   66,
       39,   54,   62,   58,   60,   46,   57,   48,   47,   65,
       45,   63,   55,   50,   51,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   53,   61,   44,   40,   40,   40,   41,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   67,    0,   49,    0,   65,    0,
       43,   56,   59,   52,   64,   64,   64,   64,   64,   64,

       64,    8,   64,   64,   64,   64,   64,   15,   16,   64,
       64,   64,   64,   21,   22,   64,   64,   64,   64,   31,
       64,   64,   64,   64,   64,   64,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,    8,   40,   40,   40,   40,   40,   15,
       16,   40,   40,   40,   40,   21,   22,   40,   40,   40,
       40,   31,   40,   40,   40,   40,   40,   40,    0,    0,
       65,    0,   65,    1,   64,   64,   64,   64,   64,    7,
       64,   64,   11,   64,   13,   64,   17,   18,   19,   20,
       64,   64,   64,   64,   29,   64,   64,   64,   64,   35,

       64,   64,   40,   40,   40,   40,   40,    1,   40,   40,
       40,   40,   40,    7,   40,   40,   11,   40,   13,   40,
       17,   18,   19,   20,   40,   40,   40,   40,   29,   40,
       40,   40,   40,   35,   40,   40,   42,   64,   64,    4,
       64,   64,   64,   10,   64,   64,   64,   64,   25,   64,
       64,   30,   32,   33,   64,   64,   64,   40,   40,   40,
        4,   40,   40,   40,   10,   40,   40,   40,   40,   25,
       40,   40,   30,   32,   33,   40,   40,   40,   42,    2,
        3,    5,   64,   64,   12,   64,   64,   64,   64,   64,
       64,   34,   36,   37,   40,    2,    3,    5,   40,   40,

       12,   40,   40,   40,   40,   40,   40,   34,   36,   37,
       64,    9,   64,   64,   64,   26,   27,   28,   64,   40,
        9,   40,   40,   40,   26,   27,   28,   40,    6,   64,
       64,   24,   38,    6,   40,   40,   24,   38,   14,   64,
       14,   40,   23,   23,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       28,   34,   35,   36,   37,   38,   39,   28,   40,   28,
       41,    1,   42,   43,    1,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   28,   28,   53,   54,   55,
       56,   57,   28,   58,   59,   60,   61,   62,   63,   28,
       64,   28,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[351] =
    {   0,
        0,    0,   64,    0,  125,  128,  619,  949,  949,  949,
      949,  563,  949,  949,  949,  949,  949,  494,  949,  124,
      453,  949,  121,  949,  350,  109,  113,  122,  117,  121,
      126,    0,  122,  119,  133,  156,  121,  136,  145,  160,
      152,  169,  169,  949,  949,  949,    0,    0,    0,  949,
      320,    0,    0,    0,    0,  314,    0,  185,  306,    0,
      184,    0,  299,  233,  291,  233,  205,  231,  292,  174,
      289,  287,  294,  307,  232,  181,  183,  343,  326,  328,
      337,    0,    0,    0,  271,  252,  949,  217,  341,  202,
      949,  949,  949,  949,    0,  199,  165,  233,  228,  240,

      344,  265,  327,  323,  339,  339,  347,    0,    0,  337,
      341,  358,  354,    0,    0,  361,  377,  364,  382,    0,
      371,  376,  376,  379,  388,  389,    0,  265,    0,  206,
      415,  260,    0,    0,    0,    0,  395,  397,  408,  402,
      412,  426,  416,  438,  432,  436,  439,  442,  462,  425,
      446,  466,  456,  473,  475,  449,  459,  476,  497,  486,
      480,  483,  492,  504,  502,  510,  524,  532,  210,  219,
      526,  196,  178,    0,  523,  521,  533,  387,  396,    0,
      481,  534,    0,  528,    0,  539,    0,    0,    0,    0,
      544,  542,  539,  543,    0,  544,  554,  555,  552,    0,

      554,  550,  278,  594,  583,  149,  144,  565,  574,  582,
      569,  585,  588,  589,  592,  591,  593,  603,  601,  604,
      605,  606,  609,  612,  638,  620,  623,  625,  633,  635,
      641,  646,  647,  649,  653,  655,  315,  640,  654,    0,
      651,  660,  657,    0,  652,  660,  654,  664,  676,  673,
      689,    0,    0,    0,  681,  689,  690,  720,  695,  705,
      691,  696,  698,  719,  702,  703,  722,  717,  718,  739,
      738,  750,  726,  740,  741,  752,  754,  755,  141,    0,
        0,    0,  712,  748,    0,  756,  762,  766,  759,  769,
      757,    0,    0,  766,  354,  774,  776,  778,  783,  788,

      784,  798,  790,  804,  810,  806,  807,  792,  811,  816,
      812,    0,  815,  812,  821,    0,    0,    0,  825,  834,
      838,  840,  839,  847,  843,  845,  851,  858,    0,  847,
      845,    0,    0,  860,  861,  871,  862,  867,    0,  874,
      875,  884,    0,  888,  949,  139,  936,  939,  942,  945
    } ;

static yyconst flex_int16_t yy_def[351] =
    {   0,
      345,    1,  345,    3,    1,    1,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  345,  345,  345,  347,  347,  347,  345,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  348,  348,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,  347,  347,  347,  345,  349,  345,  345,  345,  345,
      345,  345,  345,  345,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  347,  350,  347,  347,
      347,  347,  347,  347,  347,  347,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,  349,  349,
      345,  345,  345,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  350,  350,  347,  347,  347,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,  349,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  350,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,  349,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  350,   65,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
      346,  346,  346,  346,  346,  346,  346,  346,  346,   65,
       65,   65,   65,   65,   65,   65,   65,   65,  346,  346,
      346,  346,  346,   65,   65,   65,   65,   65,  346,  346,
       65,   65,  346,   65,    0,  345,  345,  345,  345,  345
    } ;

static yyconst flex_int16_t yy_nxt[1014] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   32,   33,   32,   32,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   32,
       44,   45,   46,   26,   27,   28,   29,   30,   31,   32,
       32,   33,   32,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   32,   47,   48,   49,   50,   51,   47,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   70,
       71,   70,   70,   72,   73,   74,   75,   76,   77,   78,

       79,   80,   81,   70,   82,   83,   84,   64,   65,   66,
       67,   68,   69,   70,   70,   71,   70,   72,   73,   74,
       75,   76,   77,   78,   79,   80,   81,   70,    8,   85,
        8,    8,   85,    8,   88,   98,   89,   92,   93,   96,
       99,   95,   97,  101,  105,  108,   90,  170,  102,  103,
      110,  104,  109,  100,  116,  111,  207,  106,  117,  112,
       98,  207,  107,   96,  113,   99,   97,  118,  101,  105,
      108,   90,  102,  103,  110,  104,  109,  100,  116,  114,
      111,  106,  123,  117,  112,  119,  107,  124,  113,  115,
      173,  120,  118,  121,  125,  130,  137,  131,  175,  122,

      134,  135,  126,  159,  114,  160,  123,  132,  173,  172,
      119,  172,  124,  115,  173,  120,  170,  121,  205,  125,
      174,  137,  175,  122,  237,  170,  126,  137,  159,  171,
      160,  143,  132,  127,  127,  127,  144,  127,  127,  127,
      127,  127,  127,  127,  127,  174,  127,  127,  127,  127,
      127,  141,  137,  137,  137,  137,  143,  176,  170,  145,
      144,  146,  177,  138,  142,  158,  139,  206,  169,  206,
      178,  204,  207,  127,  127,  127,  141,   86,  137,  137,
      137,  169,  176,  145,  204,  146,  177,  138,  142,  158,
      139,  127,  127,  127,  178,  127,  127,  127,  127,  127,

      127,  127,  127,  181,  127,  127,  127,  127,  127,  137,
      147,  137,  150,  140,  137,  136,  153,  279,  152,  151,
      154,  170,  133,  148,  129,  155,  128,  181,  149,  137,
      156,  127,  127,  127,  137,  147,  137,  150,  140,  137,
      157,  153,  152,  151,  183,  154,  166,  148,  137,  155,
      137,   88,  149,   89,  137,  156,  165,  169,  187,  137,
      204,  182,  167,   90,  157,  137,   94,  184,  161,  183,
      168,  166,  185,  137,  162,  137,  163,  186,  179,  188,
      165,  180,  164,  187,  137,  182,  189,  167,   90,  190,
      137,  184,  191,  161,  168,  192,  185,  193,  162,  195,

      163,  186,  179,  188,  196,  180,  164,  197,  198,  194,
      189,  199,  200,  190,  201,  202,  191,  137,  208,  137,
      192,  241,  193,  195,  137,  130,  210,  131,  242,  196,
      137,  197,  198,  194,  137,  199,  200,  132,  137,  201,
      202,  209,  137,  208,  137,  241,  211,  137,  137,  137,
      213,  210,  242,  214,  137,  137,  212,  217,  137,  137,
      137,  137,  132,  137,  137,  209,  216,  218,  137,   91,
      211,  137,  137,  137,  213,  219,  215,  214,  137,  137,
      212,  137,  217,  137,  137,  137,  137,  221,  137,  137,
      216,  218,  220,  137,  222,  137,  137,  137,  137,  219,

      215,  223,  230,  137,   87,  137,  137,  225,  137,  137,
      224,  243,  221,  137,  137,  226,  220,  227,  222,  137,
      137,  229,  137,  137,  137,  223,  137,  230,  231,  228,
      137,  225,  137,  137,  224,  243,  232,  233,  171,  137,
      226,  238,  227,  234,  137,  229,  137,  239,   90,  137,
      235,  137,  231,  228,  137,  240,  244,  137,  236,  246,
      232,  233,  245,  249,  247,  251,  238,  234,  248,   86,
      250,  137,  239,   90,  252,  235,  253,  254,  255,  137,
      240,  244,  256,  236,  246,  257,  245,  137,  249,  247,
      251,  261,  259,  248,  250,  205,  137,  169,  252,  258,

      204,  253,  254,  255,  137,  132,  256,  137,  260,  257,
      137,  137,  137,  265,  137,  137,  261,  259,  345,  262,
      263,  137,  264,  137,  267,  137,  137,  137,  137,  137,
      132,  137,  137,  260,  137,  137,  137,  266,  265,  137,
      137,  270,  137,  262,  263,  137,  264,  272,  137,  267,
      137,  137,  137,  137,  271,  137,  137,  137,  268,  137,
      137,  266,  269,  274,  345,  273,  270,  137,  275,  137,
      137,  137,  272,  276,  285,  137,  287,  137,  271,  280,
      137,  277,  137,  268,  281,  137,  282,  269,  274,  273,
      278,  283,  284,  275,  137,  286,  137,  288,  276,  285,

      137,  287,  137,  280,  289,  277,  290,  291,  281,  292,
      282,  293,  294,  137,  278,  283,  284,  137,  137,  286,
      137,  288,  295,  169,  137,  301,  204,  137,  289,  299,
      290,  298,  291,  292,  296,  297,  293,  294,  137,  303,
      137,  137,  137,  137,  137,  137,  311,  345,  137,  137,
      301,  304,  137,  299,  300,  298,  345,  302,  296,  297,
      137,  137,  137,  137,  303,  137,  137,  305,  307,  137,
      311,  306,  137,  137,  137,  304,  309,  310,  300,  312,
      308,  302,  313,  314,  315,  137,  137,  137,  137,  316,
      317,  305,  318,  307,  319,  306,  137,  137,  137,  137,

      137,  309,  310,  312,  308,  137,  137,  313,  314,  315,
      137,  323,  137,  316,  137,  317,  318,  320,  319,  321,
      137,  137,  324,  137,  322,  137,  137,  326,  137,  137,
      137,  137,  137,  137,  329,  137,  323,  137,  137,  137,
      325,  320,  327,  321,  328,  137,  330,  324,  331,  322,
      332,  137,  326,  137,  137,  333,  334,  137,  137,  329,
      137,  137,  137,  137,  325,  137,  327,  137,  328,  137,
      330,  335,  331,  137,  332,  336,  337,  339,  340,  333,
      137,  334,  137,  137,  137,  137,  137,  137,  338,  137,
      137,  341,  137,  137,  137,  335,  343,  137,  137,  336,

      337,  339,  340,  345,  342,  137,  344,  137,  137,  137,
      137,  345,  338,  345,  137,  341,  345,  345,  137,  345,
      345,  343,  137,  345,  345,  345,  345,  345,  342,  345,
      345,  344,  345,  345,  345,  137,  127,  345,  127,  137,
      345,  137,  169,  169,  169,  203,  203,  203,    7,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345
    } ;

static yyconst flex_int16_t yy_chk[1014] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    5,
        5,    6,    6,    6,   20,   27,   20,   23,   23,   26,
       28,  346,   26,   29,   31,   33,   20,  279,   29,   30,
       34,   30,   33,   28,   37,   35,  207,   31,   38,   35,
       27,  206,   31,   26,   35,   28,   26,   39,   29,   31,
       33,   20,   29,   30,   34,   30,   33,   28,   37,   36,
       35,   31,   41,   38,   35,   40,   31,   42,   35,   36,
      173,   40,   39,   40,   43,   58,   70,   58,   97,   40,

       61,   61,   43,   76,   36,   77,   41,   58,  172,   90,
       40,   90,   42,   36,   90,   40,  169,   40,  130,   43,
       96,   70,   97,   40,  170,  170,   43,   67,   76,   88,
       77,   67,   58,   64,   64,   64,   67,   64,   64,   64,
       64,   64,   64,   64,   64,   96,   64,   64,   64,   64,
       64,   66,   67,   68,   75,   66,   67,   98,   86,   68,
       67,   68,   99,   64,   66,   75,   64,  132,  128,  132,
      100,  128,  132,   64,   64,   64,   66,   85,   68,   75,
       66,  203,   98,   68,  203,   68,   99,   64,   66,   75,
       64,   65,   65,   65,  100,   65,   65,   65,   65,   65,

       65,   65,   65,  102,   65,   65,   65,   65,   65,   72,
       69,   71,   71,   65,   69,   63,   73,  237,   72,   71,
       73,  237,   59,   69,   56,   73,   51,  102,   69,   74,
       74,   65,   65,   65,   72,   69,   71,   71,   65,   69,
       74,   73,   72,   71,  104,   73,   80,   69,   79,   73,
       80,   89,   69,   89,   74,   74,   79,  295,  110,   81,
      295,  103,   81,   89,   74,   78,   25,  105,   78,  104,
       81,   80,  106,   79,   78,   80,   78,  107,  101,  111,
       79,  101,   78,  110,   81,  103,  112,   81,   89,  113,
       78,  105,  116,   78,   81,  117,  106,  117,   78,  118,

       78,  107,  101,  111,  119,  101,   78,  121,  122,  117,
      112,  123,  124,  113,  125,  126,  116,  137,  138,  138,
      117,  178,  117,  118,  140,  131,  140,  131,  179,  119,
      139,  121,  122,  117,  141,  123,  124,  131,  143,  125,
      126,  139,  137,  138,  138,  178,  141,  150,  142,  140,
      143,  140,  179,  143,  145,  139,  142,  146,  146,  141,
      144,  147,  131,  143,  148,  139,  145,  147,  151,   21,
      141,  156,  150,  142,  143,  148,  144,  143,  153,  145,
      142,  157,  146,  146,  149,  144,  147,  152,  152,  148,
      145,  147,  149,  151,  153,  154,  156,  155,  158,  148,

      144,  154,  161,  153,   18,  162,  157,  158,  160,  149,
      155,  181,  152,  152,  163,  159,  149,  159,  153,  159,
      154,  160,  155,  158,  165,  154,  164,  161,  163,  159,
      162,  158,  166,  160,  155,  181,  164,  165,  171,  163,
      159,  175,  159,  166,  159,  160,  167,  176,  171,  165,
      167,  164,  163,  159,  168,  177,  182,  166,  168,  186,
      164,  165,  184,  192,  191,  194,  175,  166,  191,   12,
      193,  167,  176,  171,  196,  167,  197,  198,  199,  168,
      177,  182,  201,  168,  186,  202,  184,  208,  192,  191,
      194,  211,  209,  191,  193,  205,  209,  204,  196,  204,

      204,  197,  198,  199,  210,  205,  201,  212,  210,  202,
      213,  214,  208,  216,  215,  217,  211,  209,    7,  212,
      213,  209,  215,  219,  220,  218,  220,  221,  222,  210,
      205,  223,  212,  210,  224,  213,  214,  218,  216,  215,
      217,  226,  226,  212,  213,  227,  215,  228,  219,  220,
      218,  220,  221,  222,  227,  229,  223,  230,  225,  224,
      225,  218,  225,  231,    0,  230,  226,  226,  232,  233,
      227,  234,  228,  233,  245,  235,  247,  236,  227,  238,
      229,  235,  230,  225,  239,  225,  241,  225,  231,  230,
      236,  242,  243,  232,  233,  246,  234,  248,  233,  245,

      235,  247,  236,  238,  249,  235,  250,  251,  239,  255,
      241,  256,  257,  261,  236,  242,  243,  259,  262,  246,
      263,  248,  258,  258,  265,  266,  258,  260,  249,  263,
      250,  262,  251,  255,  259,  260,  256,  257,  261,  268,
      269,  264,  259,  262,  267,  263,  283,    0,  273,  265,
      266,  269,  260,  263,  264,  262,    0,  267,  259,  260,
      271,  270,  274,  275,  268,  269,  264,  270,  272,  267,
      283,  271,  272,  273,  276,  269,  277,  278,  264,  284,
      276,  267,  286,  287,  288,  271,  270,  274,  275,  289,
      290,  270,  291,  272,  294,  271,  296,  272,  297,  276,

      298,  277,  278,  284,  276,  299,  301,  286,  287,  288,
      300,  303,  303,  289,  308,  290,  291,  299,  294,  300,
      302,  296,  304,  297,  302,  298,  304,  306,  306,  307,
      299,  301,  305,  309,  311,  300,  303,  303,  310,  308,
      305,  299,  307,  300,  310,  302,  313,  304,  314,  302,
      315,  304,  306,  306,  307,  319,  320,  305,  309,  311,
      321,  323,  322,  310,  305,  325,  307,  326,  310,  324,
      313,  322,  314,  327,  315,  323,  324,  330,  331,  319,
      328,  320,  334,  335,  337,  321,  323,  322,  328,  338,
      325,  335,  326,  336,  324,  322,  340,  341,  327,  323,

      324,  330,  331,    0,  336,  328,  342,  334,  335,  337,
      344,    0,  328,    0,  338,  335,    0,    0,  336,    0,
        0,  340,  341,    0,    0,    0,    0,    0,  336,    0,
        0,  342,    0,    0,    0,  344,  347,    0,  347,  348,
        0,  348,  349,  349,  349,  350,  350,  350,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analyzer.lex"
#line 2 "analyzer.lex"

#include "tokenconsts.h"
#include <iostream>
#include <iomanip>

static char* text;
static const int subtractFromToken = 257;

static const char* tokenNames[] = {
	"yand",
	"yarray",
	"yassign",
	"ybegin",
	"ycaret",
	"ycase",
	"ycolon",
	"ycomma",
	"yconst",
	"ydispose",
	"ydiv",
	"ydivide",
	"ydo",
	"ydot",
	"ydotdot",
	"ydownto",
	"yelse",
	"yend",
	"yequal",
	"yfalse",
	"yfor",
	"yfunction",
	"ygreater",
	"ygreaterequal",
	"yident",
	"yif",
	"yin",
	"yleftbracket",
	"yleftparen",
	"yless",
	"ylessequal",
	"yminus",
	"ymod",
	"ymultiply",
	"ynew",
	"ynil",
	"ynot",
	"ynotequal",
	"ynumber",
	"yof",
	"yor",
	"yplus",
	"yprocedure",
	"yprogram",
	"yread",
	"yreadln",
	"yrecord",
	"yrepeat",
	"yrightbracket",
	"yrightparen",
	"ysemicolon",
	"yset",
	"ystring",
	"ythen",
	"yto",
	"ytrue",
	"ytype",
	"yuntil",
	"yvar",
	"ywhile",
	"ywrite",
	"ywriteln",
	"yunknown"
};

static const int nextToken = -1;



#line 879 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 88 "analyzer.lex"

	/** Identifiers **/
#line 1071 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 346 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 949 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "analyzer.lex"
{ return yand; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 91 "analyzer.lex"
{ return yarray; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 92 "analyzer.lex"
{ return ybegin; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 93 "analyzer.lex"
{ return ycase; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 94 "analyzer.lex"
{ return yconst; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 95 "analyzer.lex"
{ return ydispose; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 96 "analyzer.lex"
{ return ydiv; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 97 "analyzer.lex"
{ return ydo; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "analyzer.lex"
{ return ydownto; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "analyzer.lex"
{ return yelse; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "analyzer.lex"
{ return yend; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "analyzer.lex"
{ return yfalse; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "analyzer.lex"
{ return yfor; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "analyzer.lex"
{ return yfunction; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "analyzer.lex"
{ return yif; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "analyzer.lex"
{ return yin; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "analyzer.lex"
{ return ymod; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "analyzer.lex"
{ return ynew; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "analyzer.lex"
{ return ynil; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "analyzer.lex"
{ return ynot; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "analyzer.lex"
{ return yof; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "analyzer.lex"
{ return yor; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "analyzer.lex"
{ return yprocedure; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "analyzer.lex"
{ return yprogram; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 114 "analyzer.lex"
{ return yread; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 115 "analyzer.lex"
{ return yreadln; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "analyzer.lex"
{ return yrecord; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "analyzer.lex"
{ return yrepeat; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "analyzer.lex"
{ return yset; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "analyzer.lex"
{ return ythen; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "analyzer.lex"
{ return yto; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 121 "analyzer.lex"
{ return ytrue; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "analyzer.lex"
{ return ytype; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "analyzer.lex"
{ return yuntil; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 124 "analyzer.lex"
{ return yvar; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 125 "analyzer.lex"
{ return ywhile; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "analyzer.lex"
{ return ywrite; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 127 "analyzer.lex"
{ return ywriteln; }
	YY_BREAK
/** Operands **/
case 39:
YY_RULE_SETUP
#line 129 "analyzer.lex"
{ yymore(); BEGIN(STRING); return nextToken; }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 130 "analyzer.lex"
{ yymore(); return nextToken; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 131 "analyzer.lex"
{ text = yytext; BEGIN(0); return ystring; }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 132 "analyzer.lex"
{ text = yytext; BEGIN(0); return ystring; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 133 "analyzer.lex"
{ ECHO; return nextToken; }
	YY_BREAK
/**
<INITIAL>(\(\*)		{ printf("/*"); BEGIN(COMMENT); return nextToken; }
<COMMENT>[^*)]*		{ ECHO; return nextToken; }
<COMMENT>[*]		{ 
				register int peek = input();
				if (peek == ')') {
					printf("*\/");
					BEGIN(0);
				} else {
					unput(peek);
					ECHO;
				}
				return nextToken;
			}
<COMMENT><<EOF>>	{ printf("*\/"); BEGIN(0); return nextToken; }
	**/
case 43:
YY_RULE_SETUP
#line 150 "analyzer.lex"
{ return yassign; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 151 "analyzer.lex"
{ return ycaret; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 152 "analyzer.lex"
{ return ycolon; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 153 "analyzer.lex"
{ return ycomma; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 154 "analyzer.lex"
{ return ydivide; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "analyzer.lex"
{ return ydot; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 156 "analyzer.lex"
{ return ydotdot; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 157 "analyzer.lex"
{ return yequal; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 158 "analyzer.lex"
{ return ygreater; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 159 "analyzer.lex"
{ return ygreaterequal; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 160 "analyzer.lex"
{ return yleftbracket; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 161 "analyzer.lex"
{ return yleftparen; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 162 "analyzer.lex"
{ return yless; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 163 "analyzer.lex"
{ return ylessequal; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 164 "analyzer.lex"
{ return yminus; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 165 "analyzer.lex"
{ return ymultiply; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 166 "analyzer.lex"
{ return ynotequal; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 167 "analyzer.lex"
{ return yplus; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 168 "analyzer.lex"
{ return yrightbracket; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 169 "analyzer.lex"
{ return yrightparen; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 170 "analyzer.lex"
{ return ysemicolon; }
	YY_BREAK
/** Misc */
case 64:
YY_RULE_SETUP
#line 172 "analyzer.lex"
{ text = yytext; return yident; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 173 "analyzer.lex"
{ text = yytext; return ynumber; }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 174 "analyzer.lex"
/** Ignore */
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 175 "analyzer.lex"
{ text = yytext; return yunknown; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 177 "analyzer.lex"
ECHO;
	YY_BREAK
#line 1525 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 346 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 346 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 345);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 177 "analyzer.lex"



int getNewTokenId(int oldTokenId)
{
	int newTokenId = oldTokenId - subtractFromToken;
	return newTokenId;
}

void displayToken(int tokenId)
{
	std::string tName;
	tName = tokenNames[getNewTokenId(tokenId)];

	std::cout << std::left << std::setw(8) <<  tokenId;
	std::cout << std::left << std::setw(15) << tokenNames[tokenId-257];
	if ( (tName == "ynumber") || (tName == "yident") || (tName == "yunknown") || (tName == "ystring") ){
		std::cout << text;
	}
	std::cout << "\n";	
}

int main(void)
{
	while (1)
	{
		int tokenId = yylex();
		if (tokenId == 0) {
			break;
		} else if (tokenId > 0) {
			displayToken(tokenId);
		}
	}
	return 0;
}


